config/routes.rb
Rails.application.routes.draw do
  root "recipes#index"

  devise_for :users
  
  resources :recipes do
    member do
      post :vote
    end

    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end
  end
  resources :categories
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  has_many :post_categories
  has_many :recipes, through: :post_categories

  validates :name, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :recipe
  has_many :votes, as: :voteable
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :category
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
  
  belongs_to :user
  has_many :post_categories
  has_many :categories, through: :post_categories
  has_many :comments
  has_many :votes, as: :voteable

  validates :title, :url, :description, presence: true

  def total_votes
    up_votes - down_votes
  end

  def up_votes
    self.votes.where(vote: true).size
  end

  def down_votes
    self.votes.where(vote: false).size
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  #extend FriendlyId
  #friendly_id :email, use: :slugged

  has_many :recipes
  has_many :comments
  has_many :votes
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :voteable, polymorphic: true

  validates_uniqueness_of :user, scope: [:voteable_id, :voteable_type]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_filter :set_category, only: [:show, :edit, :update, :destroy]
  #before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @categories = Category.paginate(:page => params[:page], :per_page => 30)
  end

  def show
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @categories.update(category_params)
      redirect_to @category
    else
      render :edit
    end
  end

  def destroy
    if @category.destroy
      redirect_to categories_path
    else
      redirect_to categories_path
    end
  end

  private

  def category_params
    params.require(:category).permit!
  end

  def set_category
    @category = Category.friendly.find(params[:id])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @recipe = Recipe.friendly.find(params[:recipe_id])
    @comment = @recipe.comments.create(params.require(:comment).permit!)
    @comment.user = current_user

    if @comment.save
      redirect_to recipe_path(@recipe)
    else
      render :new
    end
  end

end

app/controllers/recipes_controller.rb
require 'will_paginate/array' 

class RecipesController < ApplicationController

  before_action :set_recipe, only: [:show, :edit, :update, :destroy, :vote]
  before_action :authenticate_user!, only: [:new, :create, :update, :destroy, :vote]

  def index
    @recipes = Recipe.paginate(:page => params[:page], :per_page => 30).sort_by{|x| x.total_votes}.reverse
  end

  def show
    @comment = Comment.new
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)
    if @recipe.save
      redirect_to recipes_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe
    else
      render :edit
    end
  end

  def destroy
    if @recipe.destroy
      redirect_to recipes_path
    else
      redirect_to @recipe
    end
  end

  def vote
    @vote = Vote.create(voteable: @recipe, user: current_user, vote: params[:vote])

    if @vote.valid?
      flash[:notice] = "Vote counted"
    else
      flash[:error] = "Vote not counted"
    end

    redirect_to :back
  end

  private

  def recipe_params
    params.require(:recipe).permit!
  end

  def set_recipe
    @recipe = Recipe.friendly.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <%= render 'shared/errors', obj: @category %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<% @categories.each do |category| %>
  <p><%= link_to category.name, category_path(category) %> | <%= link_to 'Edit', edit_category_path(category) %></p>
<% end %>

<%= link_to "New", new_category_path %>

<div>
  <%= will_paginate @categories %>
</div>

app/views/categories/new.html.erb
<h1>New</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<div>
  <ul>
    <% @category.recipes.each do |recipe| %>
      <li>Recipe: <%= link_to recipe.title, recipe_path(recipe) %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recipeit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  

  <div>
    <% flash.each do |key, value| %>
      <p><%= value %></p>
    <% end %>
  </div>

<%= yield %>

</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <%= render 'shared/errors', obj: @recipe %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
      <% cb.label {cb.check_box + cb.text} %>
    <% end %>
  </div>
  <div>
    <%= f.submit %>
  </div>

<% end %>

app/views/recipes/index.html.erb
<h1>Recipes</h1>

<% @recipes.each do |recipe| %>
  <p><%= link_to recipe.title, recipe_path(recipe) %> | <%= link_to 'Edit', edit_recipe_path(recipe) %> 
    | 
      <%= link_to vote_recipe_path(recipe, vote: true), method: 'post' do %>
        <span>up</span>
      <% end %>
    |
    Votes: <%= recipe.total_votes %>
    |
      <%= link_to vote_recipe_path(recipe, vote: false), method: 'post' do %>
        <span>down</span>
      <% end %>
<% end %></p>

<%= link_to 'New', new_recipe_path %>

<div>
  <%#= will_paginate @recipes %>
</div>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form' %>

app/views/recipes/show.html.erb
<h1><%= @recipe.title %></h1>

<div>
  <ul>
    <% @recipe.categories.each do |category| %>
      <li>Category: <%= link_to category.name, category_path(category) %></li>
    <% end %>
  </ul>
</div>

<h2>Comments</h2>
<hr>

<% @recipe.comments.each do |comment| %>
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
<% end %>

<h2>Add Comment</h2>

<%= form_for([@recipe, @comment]) do |f| %>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <div>
    <%= f.submit %>
  </div>

<% end %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div>
    <h2><%= pluralize(obj.errors.count , "error") %> prevented save</h2>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>